runtime: nodejs18
handlers:

- url: /(.*\..+)$
  static_files: dist/\1
  upload: dist/(.*\..+)$

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  # secure: always
  # redirect_http_response_code: 301
  # http_headers:
  #   Strict-Transport-Security: max-age=31536000; includeSubDomains
  #   X-Frame-Options: DENY
  #   X-XSS-Protection: 1; mode=block
  #   X-Content-Type-Options: nosniff
  #   Referrer-Policy: same-origin
  #   Content-Security-Policy: default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'; object-src 'none'; connect-src 'self' XXXXXXXXXXXXXXXXXXXXXXXXXX; font-src 'self' data:; form-action 'self'
  #   Cache-Control: no-cache, no-store, must-revalidate
  #   Pragma: no-cache
  #   Expires: 0
  #   Access-Control-Allow-Origin: "*"
  #   Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
  #   Access-Control-Allow-Headers: