name: Micro Apps deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '15.x'

    - name: Install
      run: npm install

    - name: Build
      run: npm run build

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: "read"
#       id-token: "write"

#     steps:
#       - id: "checkout"
#         uses: "actions/checkout@v4"

#       - id: "auth"
#         uses: "google-github-actions/auth@v2"
#         with:
#           workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
#           service_account: "my-service-account@my-project.iam.gserviceaccount.com"

#       - id: "upload-folder"
#         uses: "google-github-actions/upload-cloud-storage@v2"
#         with:
#           path: "/path/to/folder"
#           destination: "bucket-name"

#         # Example of using the output
#       - id: "uploaded-files"
#         uses: "foo/bar@v1"
#         env:
#           files: "${{ steps.upload-folder.outputs.uploaded }}"
